
import type { App } from "@/lib/types"

export const marketplaceApps: App[] = [
    {
        id: "1",
        name: "Faded Aesthetic",
        description: "Soft, washed-out textures with a nostalgic soul.",
        image: "/marketplace/bg1.mp4",
        tags: ["Style", "Film"],
        creditCost: 5,
        isNew: true,
    },
    {
        id: "2",
        name: "Cinematic Motion",
        description: "Dynamic temporal shifts for cinematic storytelling.",
        image: "/marketplace/bg2.mp4",
        tags: ["Video", "Motion"],
        creditCost: 10,
        isPro: true,
    },
    {
        id: "3",
        name: "Neural Bloom",
        description: "Organic recursive patterns inspired by living logic.",
        image: "/marketplace/bg3.mp4",
        tags: ["Abstract", "AI"],
        creditCost: 8,
    },
    {
        id: "4",
        name: "Ethereal Depth",
        description: "Deep spatial awareness in every pixel.",
        image: "/marketplace/bg4.mp4",
        tags: ["3D", "Atmospheric"],
        creditCost: 3,
    },
    {
        id: "5",
        name: "Glitch Resonance",
        description: "Digital artifacts turned into harmonic visual noise.",
        image: "/marketplace/bg5.mp4",
        tags: ["Cyber", "VFX"],
        creditCost: 2,
    },
    {
        id: "6",
        name: "Minimalist Pulse",
        description: "Clean, fundamental forms for pure conceptualization.",
        image: "/marketplace/bg6.mp4",
        tags: ["Design", "Static"],
        creditCost: 12,
    },
    {
        id: "7",
        name: "Hyper-Contrast",
        description: "Extreme lighting for maximum emotional impact.",
        image: "/marketplace/bg7.mp4",
        tags: ["Noir", "Lighting"],
        creditCost: 7,
        isNew: true,
    },
    {
        id: "8",
        name: "Dream Sequence",
        description: "Surrealistic interpretations of latent imagination.",
        image: "/marketplace/bg8.mp4",
        tags: ["Dreams", "Latent"],
        creditCost: 15,
        isPro: true,
    },
]
